modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "ARR"

[[mods]]
modId = "zombie_variants"
version = "${version}"
displayName = "Zombie Variants"
authors = "Lupin, Craft1x"
description = '''
Adds 15 unique zombie variants, each appearing in specific biomes for you to encounter
'''
logoFile = "icon.png"

[[dependencies.zombie_variants]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.zombie_variants]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.zombie_variants]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
